/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************

 */
	#include "file.h"

	// ================= GLOBALS =================
	volatile uint32_t msTicks = 0;
	FaultType faultType = NO_FAULT;
	uint8_t pir_ready = 0;             // startup PIR filter
    bool active = false;

	//uint8_t fault_check_enable = 0;

	// ================= TIM3 ISR (1 ms tick) =================
	void TIM3_IRQHandler(void)
	{
		if (TIM3->SR & 1U)              // UIF
		{
			TIM3->SR &= ~1U;            // clear UIF
			msTicks++;
		}
	}

	uint32_t millis(void)
	{
		return msTicks;
	}

	// ================= CLOCK INIT (8 MHz HSI) =================
	static void Clock_Init(void)
	{
		RCC->CR |= 1U;                  // HSI ON
		while (!(RCC->CR & (1U << 1))); // HSI ready
		RCC->CFGR = 0;                  // SYSCLK = HSI
	}

	// ================= TIM3 INIT (1 ms) =================
	void TIM3_Init(void)
	{
		RCC->APB1ENR |= (1U << 1);       // TIM3 clock

		TIM3->PSC = 8000 - 1;            // 8 MHz / 8000 = 1 kHz
		TIM3->ARR = 1;                   // 1 ms
		TIM3->CNT = 0;

		TIM3->DIER |= 1U;                // UIE
		TIM3->CR1  |= 1U;                // CEN

		NVIC_SetPriority(TIM3_IRQn, 0);
		NVIC_EnableIRQ(TIM3_IRQn);
	}

	// ================= GPIO INIT =================
	void GPIO_Init(void)
	{
		RCC->AHBENR |= (1U << 17) | (1U << 18);   // GPIOA + GPIOB

		// PA1..PA5 output, PA10 input
		GPIOA->MODER &= ~(
			(3U<<(1*2)) | (3U<<(2*2)) |
			(3U<<(3*2)) | (3U<<(4*2)) |          //Clearing the bit respective bit position
			(3U<<(5*2)) | (3U<<(10*2))
		);

		GPIOA->MODER |= (
			(1U<<(1*2)) | (1U<<(2*2)) |
			(1U<<(3*2)) | (1U<<(4*2)) |
			(1U<<(5*2))
		);

		GPIOB->MODER |= (3U << (1 * 2));                               // PB1 analog
		GPIOA->BRR = LED1 | LED2 | RELAY_LOAD | RELAY_STAT | PIR_PWR; //Reset all the state
	}

	// ================= ADC INIT =================
	void ADC_Init(void)
	{
		RCC->CR2 |= 1U;                  // HSI14 ON
		while (!(RCC->CR2 & 2U));

		RCC->APB2ENR |= (1U << 9);        // ADC clock

		ADC1->CR |= (1U << 31);           // ADCAL
		while (ADC1->CR & (1U << 31));

		ADC1->CHSELR = (1U << 9);         // IN9 (PB1)
		ADC1->CR |= 1U;                   // ADEN
		while (!(ADC1->ISR & 1U));
	}

	uint16_t ADC_Read(void)
	{
		ADC1->CR |= (1U << 2);            // ADSTART
		while (!(ADC1->ISR & (1U << 2)));
		return ADC1->DR;
	}

	// ================= MAIN =================
	int main(void)
	{
		Clock_Init();
		GPIO_Init();
		ADC_Init();
		TIM3_Init();

		// Power ON indication
		PIN_SET(LED1);

		// PIR warm-up
		PIN_SET(PIR_PWR);  // MOSFET ON
		uint32_t t0 = millis();
		while ((millis() - t0) < PIR_WARMUP_MS);  //2 sec warm up time of sensor


		uint32_t fault_arm_time = millis();
		uint32_t lastMotion = 0;
		uint32_t lastBlink  = 0;
		uint32_t lastPirLowTime = 0;

	    uint8_t fault_check_enable = 0;
		uint8_t open_cnt = 0, short_cnt = 0;

		bool blink  = false;

		while (1)
		{
			uint32_t now = millis();
		    uint16_t adc = ADC_Read();

			// ---- ENABLE FAULT CHECK AFTER SENSOR STABLE ------
			if (!fault_check_enable)
			{
				if ((now - fault_arm_time) >= 3000)   // 3 sec delay for stabling the sensor
					fault_check_enable = 1;
			}

			// ---- FAULT DETECTION ----
			if (fault_check_enable && (faultType == NO_FAULT|| faultType == HIGH_STUCK_FAULT))
			{
				if (adc < OPEN_TH)
				{
					open_cnt++;
					short_cnt = 0;
					if (open_cnt >= 3)
						faultType = OPEN_FAULT;
				}
				else if (adc > SHORT_TH)
				{
					short_cnt++;
					open_cnt = 0;
					if (short_cnt >= 3)
						faultType = SHORT_FAULT;
				}
				else
				{
					open_cnt = 0;
					short_cnt = 0;

					if(faultType == HIGH_STUCK_FAULT)
					faultType = NO_FAULT;
				}
			}

			// ---- FAULT MODE ----
			if (faultType != NO_FAULT)
			{
				RELAY_ON(RELAY_LOAD);

				if (now - lastBlink >= FAULT_BLINK_MS)
				{
					lastBlink = now;
					blink = !blink;
					blink ? PIN_SET(LED2) : PIN_CLR(LED2);
					blink ? RELAY_ON(RELAY_STAT) : RELAY_OFF(RELAY_STAT);
				}
				continue;
			}

			if (!pir_ready)
			    {
			        if ((GPIOA->IDR & PIR_PIN) == 0)
			        {
			            pir_ready = 1;                // clean LOW seen
			        }
			            continue;                    // ignore PIR till then
			    }
			// ---- NORMAL MODE ----

			bool pir = (GPIOA->IDR & PIR_PIN);

			// ---- TRACK LAST LOW EVENT ----
			if (!pir)
			{
			    lastPirLowTime = now;
			}

			// ---- NORMAL MOTION CONTROL ----

			if (pir)
			{
			    lastMotion = now;

			    if (!active)
			    {
			        active = true;
			        PIN_SET(LED2);
			        RELAY_ON(RELAY_LOAD);
			        RELAY_ON(RELAY_STAT);
			    }
			}
			else
			{
			    if (active && (now - lastMotion >= MOTION_HOLD_MS))
			    {
			        active = false;
			        PIN_CLR(LED2);
			        RELAY_OFF(RELAY_LOAD);
			        RELAY_OFF(RELAY_STAT);
			    }
			}

			// ---- HIGH STUCK FAULT DETECTION ----

			if ((now - lastPirLowTime) >= PIR_NO_LOW_TIMEOUT && faultType == NO_FAULT)
			{
			    faultType = HIGH_STUCK_FAULT;
			}
		}
	}
